config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get "welcome/index"
  root 'welcome#index'

  resources :albums do
    resources :photos do
      resources :comments
    end
  end

  resources :photos, only: [:index]
  post '/:locale' => "application#set_locale"

end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  belongs_to :user
  has_many :photos, dependent: :destroy

  scope :is_public,->{where(private:false)}
  scope :is_private,->{where(private:true)}
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :photo
  validates :name, presence: true, length: { minimum: 3 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :commenter, presence: true
  validates :body, presence: true
  belongs_to :photo
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  # Paperclip
  # :styles=>{:small=>"320x240>",:thumb=>"80x60>"}
  has_attached_file :image, { :path=>":rails_root/public/uploads/:class/:style/:filename",
                              :url=>"/uploads/:class/:style/:filename",
                              :default_url=>"/uploads/:class/missing.png",
                              :preserve_files=>"true", }

  validates_attachment_content_type :image, :content_type => /image/

  validates :image, presence: true
  validates :title, presence: true
  belongs_to :album
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :category

  scope :is_public,->{where(private:false)}
  scope :is_private,->{where(private:true)}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :confirmable,
         :validatable
  validates :email, presence: true
  validates :username, presence: true
end

app/controllers/album_controller.rb
class AlbumController < ApplicationController

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save then
      redirect_to @album
    else
      render 'new'
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
  end

  def delete
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to articles_path
  end

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  private

  def album_params
    params.require(:album).permit(:title, :description)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @album.user_id = current_user.id
    if @album.save then
      redirect_to @album
    else
      render 'new'
    end
  end

  def edit
    @album = Album.find(params[:id])
    unless @album.user_id == current_user.id
      redirect_to albums_path
    end
  end

  def update
    @album = Album.find(params[:id])
    @album.update_attributes(album_params)
    @album.save!
    redirect_to @album
  end

  def destroy
    @album = Album.find(params[:id])
    if owner(@album)
      @album.destroy
      redirect_to albums_path
    end
  end

  def index
    @albums = Album.is_public
    unless current_user == nil
      @albums += Album.is_private.where(:user_id=>current_user.id)
    end
  end

  def show
    @album = Album.find(params[:id])
    @photos = @album.photos.is_public
    @user = User.find(@album.user_id)
    unless current_user == nil
      @photos += @album.photos.is_private.where(:user_id=>current_user.id)
    end
  end

  private

  def owner(album)
    if album == nil
      return false
    end
    if current_user == nil
      return false
    end
    unless album.user_id == current_user.id
      return false
    else
      return true
    end
  end

  def album_params
    params.require(:album).permit(:title, :description, :private)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    {:locale => I18n.locale}
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :username)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :current_password, :username)}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @comment.commenter = current_user.username
  end

  def create
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.create(comment_params)
    @comment.commenter = current_user.username
    @comment.user_id = current_user.id
    if @comment.save
      @album = Album.find(@photo.album_id)
      redirect_to album_photo_path(@album, @photo)
    end
  end

  def edit
    # not provided
  end

  def update
    # not provided
  end

  def destroy
    @album = Album.find(params[:album_id])
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to album_photo_path(@album, @photo)
  end

  def index
    # not provided
  end

  def show
    @comment = Comments.find(params[:id])
    @photo = Photo.find(params[:photo_id])
  end


  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def new
    @album = Album.find(params[:album_id])
    @categories = Category.all
    unless @album.user_id == current_user.id
      redirect_to @album
    end
  end

  def create
    @album = Album.find(params[:album_id])
    @photo = @album.photos.create(photo_params)
    @photo.user_id = current_user.id
    if @photo.save then
      redirect_to album_photo_path(@album, @photo)
    else
      render 'new'
    end
  end

  def edit
    @album = Album.find(params[:album_id])
    @photo = Photo.find(params[:id])
    @categories = Category.all
    unless @photo.user_id == current_user.id
      redirect_to album_photo_path
    end
  end

  def update
    @album = Album.find(params[:album_id])
    @photo = Photo.find(params[:id])
    @photo.update_attributes(photo_params)
    @photo.save!
    redirect_to album_photo_path(@album, @photo)
  end

  def destroy
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
    if owner(@photo)
      @photo.destroy
      redirect_to album_path(@album)
    end
  end

  def index
    @photos = Photo.is_public
    unless current_user == nil
      @photos += Photo.is_private.where(:user_id=>current_user.id)
    end
  end

  def show
    @photos = Photo.where(album_id: params[:album_id])
    @photo = Photo.find(params[:id])
    @album = Album.find(params[:album_id])
    @user = User.find(@photo.user_id)
  end


  private

  def owner(photo)
    if photo == nil
      return false
    end
    if current_user == nil
      return false
    end
    unless photo.user_id == current_user.id
      return false
    else
      return true
    end
  end

  def photo_params
    params.require(:photo).permit(:image, :title, :description, :private, category_ids: [])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @albums = Album.is_public
    unless current_user == nil
      @albums += Album.is_private.where(:user_id=>current_user.id)
    end
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_active?(test_path)
    current_page?(test_path) ? "active" : ""
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/albums/_form.html.erb
<%= bootstrap_form_for(@album) do |f| %>
    <%= f.text_field :title %>
    <%= f.text_area :description %>
    <p>
      <fieldset style="color:#2efd00;display:inline"><%= f.label :private,t('private'),:value=>true %><%= f.radio_button :private,true %></fieldset>
      <fieldset style="color:#fd7a00;display:inline"><%= f.label :private,t('public'),:value=>false %><%= f.radio_button :private,false %></fieldset>
    </p>
    <%= f.submit %>
<% end %>

app/views/albums/edit.html.erb
<h2><%= t('edit_album') %></h2>
<br/>
<%= render partial: 'form' %>
<%= link_to t('delete'),album_path(@album),class: 'btn  btn-danger',method: :delete,data:{confirm: t('confirm')} %>

app/views/albums/index.html.erb
<p>
  <% breadcrumb :albums %>
</p>

<h2><%= t('albums') %></h2>
<br/>
<%= link_to t('new_album'), new_album_path, class: 'btn btn-success' %>
<table class="table table-horizontal table-hover">
  <% @albums.each do |album| %>
      <tr>
        <div class="media">
          <th style="width:10%;">

          <% if album.photos.first %>
            <% imgPath = album.photos.first.image %>
          <% else %>
            <% imgPath = "/uploads/photos/std_image.png" %>
          <% end %>
          <%= link_to image_tag(imgPath,{height:64,width:64,:class=>'media-object'}),album_path(album),{:class=>'pull-left'} %>

          </th>
          <td style="width:60%;">
            <div class="media-body">
              <h4 class="media-heading"><%= album.title %></h4>
              <%= album.description.truncate(50) %>
            </div>
          </td>
        </div>
        <td style="text-align: right; vertical-align: middle;">
          <% if current_user != nil %>
            <% if album.user_id == current_user.id %>
              <%= link_to t('edit'),edit_album_path(album),class: 'btn  btn-info' %>
              <%= link_to t('delete'),album_path(album),class: 'btn  btn-danger',method: :delete,data:{confirm: t('confirm')} %>
            <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>
<p>
  <br/>
  <%= link_to t('to_home'), welcome_index_path, class: 'btn btn-success' %>
</p>

app/views/albums/new.html.erb
<h2><%= t('create_album') %></h2>
<br/>
<%= render partial: 'form' %>

app/views/albums/show.html.erb
<p>
  <% breadcrumb :album, @album %>
</p>

<h2><%= @album.title %></h2>
<p>
  <%= @album.description %>
</p>
<p>
  <% if @album.private %>
    <p style="color:#2efd00"><%= t('private') %></p>
  <% else %>
    <p style="color:#fd7a00"><%= t('public') %></p>
  <% end %>
  <span style="float:right">
    <%= @user.username %>
  </span>
</p>
<p>
  <br/>
  <%= link_to t('btn_back'), albums_path, class: 'btn btn-info' %>
  <%= link_to t('to_home'), welcome_index_path, class: 'btn btn-info' %>
  <% if current_user != nil %>
    <% if @album.user_id == current_user.id  %>
      <%= link_to t('edit'), edit_album_path(@album), class: 'btn  btn-info' %>
      <%= link_to t('btn_add_photo'), new_album_photo_path(@album), class: 'btn' %>
    <% end %>
  <% end %>
  <br/>
</p>

<hr>
<ul class="thumbnails">
  <%= render @photos %>
</ul>

app/views/comments/_comment.html.erb
<li class="list-group-item active">
  <p class="list-group-item-text">
    <p>
      <h7><strong><%= comment.commenter %></strong></h7>
      <h8><i>&nbsp;&nbsp;&nbsp;[<%= comment.created_at %>]</i></h8>
    </p>
    <p>
      <%= comment.body %>
    </p>
  </p>
  <p>
    <% if current_user != nil %>
      <% if @photo.user_id == current_user.id  %>
        <%= link_to t('delete_comment'),[comment.photo.album,comment.photo,comment],method: :delete,data: {confirm:'Are you sure?'} %>
      <% end %>
    <% end %>
  </p>
</li>

app/views/comments/_form.html.erb
<% if current_user == nil %>

  <%= t('comment_sign_in') %>

<% else %>

  <%= bootstrap_form_for([@album,@photo,@photo.comments.build]) do |f| %>
    <%= f.text_area :body %>
    <%= f.submit class: 'btn btn-small btn-success' %>
  <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : t('main_title') %></title>
    <%= csrf_meta_tags %>
    <!-- HTML5 shim, for IE6-8 support of HTML elements -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#"><%= t('photoblog') %></a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li class="<%= is_active?(welcome_index_path) %>"><%= link_to t('home'), welcome_index_path %></li>
              <li class="<%= is_active?(albums_path) %>"><%= link_to t('albums'), albums_path%></li>
              <li class="<%= is_active?(photos_path) %>"><%= link_to t('photos'), photos_path%></li>
            </ul>
            <ul class="nav" style="float:right">
              <% if user_signed_in? %>
                <li><%= link_to edit_user_registration_path do %><%= t('logged_in') %><strong><%= current_user.username %></strong>&nbsp;(<%= current_user.email %>)&nbsp;<% end %></li>
                <li><%= link_to t('edit_profile'),edit_user_registration_path,:class=>'navbar-link' %></li>
                <li><%= link_to t('logout'),destroy_user_session_path,method: :delete,:class=>'navbar-link' %></li>
              <% else %>
                <li><%= link_to t('sign_up'),new_user_registration_path,:class=>'navbar-link' %></li>
                <li><%= link_to t('login'),new_user_session_path,:class=>'navbar-link' %></li>
              <% end %>
              <% if I18n.locale == I18n.default_locale %>
                <li><%= link_to "DE",:locale=>'de' %></li>
                <li><%= link_to image_tag('de.png',:size=>'20x15',:border=> 0),:locale=>'de' %></li>
              <% else %>
                <li><%= link_to "EN",:locale=>'en' %></li>
                <li><%= link_to image_tag('en.png',:size=>'20x15',:border=> 0),:locale=>'en' %></li>
              <%end%>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span12">
          <%= breadcrumbs pretext: t('location'), separator: " &rsaquo; ", style: :bootstrap, display_single_fragment: true %>
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <br/>
        <p><%= t('authors') %></p>
      </footer>

    </div><!-- /container -->

  </body>
</html>

app/views/photos/_form.html.erb
<% if @photo == nil %>

  <!-- create new photo -->
  <%= bootstrap_form_for [@album, @album.photos.build],:url=>album_photos_path,html: {multipart: true} do |f| %>
      <%= f.text_field :title %>
      <%= f.text_area :description %>
      <%= f.file_field :image %>
      <p>
        <%= f.select :category_ids, @categories.map{|c| [c.name,c.id]}, {}, multiple: true %>
      </p>
      <p>
      <fieldset style="color:#2efd00;display:inline"><%= f.label :private,t('private'),:value=>true %><%= f.radio_button :private,true %></fieldset>
      <fieldset style="color:#fd7a00;display:inline"><%= f.label :private,t('public'),:value=>false %><%= f.radio_button :private,false %></fieldset>
      </p>
      <%= f.submit %>
  <% end %>

<% else %>

  <!-- edit photo -->
  <%= bootstrap_form_for [@album, @photo],html: {multipart: true} do |f| %>
    <%= f.text_field :title %>
    <%= f.text_area :description %>
    <%= image_tag @photo.image.url,:size=>'320x240' %>
    <p>
      <%= f.select :category_ids, @categories.map{|c| [c.name,c.id]}, {}, multiple: true %>
    </p>
    <p>
      <fieldset style="color:#2efd00;display:inline"><%= f.label :private,t('private'),:value=>true %><%= f.radio_button :private,true %></fieldset>
      <fieldset style="color:#fd7a00;display:inline"><%= f.label :private,t('public'),:value=>false %><%= f.radio_button :private,false %></fieldset>
    </p>
    <%= f.submit %>
  <% end %>

<% end %>

app/views/photos/_photo.html.erb
<div class="span4" style="margin-bottom:15px;">
  <div class="thumbnail">

    <%= link_to image_tag(photo.image,:alt=>'320x240'),album_photo_path(photo.album,photo) %>
    <div class="caption">
      <h3>
        <%= photo.title %>
      </h3>
      <p>
        <%= photo.description %>
      </p>
      <p>
        <% if photo.private %>
          <p style="color:#2efd00"><%= t('private') %></p>
      <% else %>
          <p style="color:#fd7a00"><%= t('public') %></p>
      <% end %>
      </p>
      <p>
        <%= link_to t('more'),album_photo_path(photo.album,photo) %>
        <span style="float:right">
          <% if current_user != nil %>
            <% if photo.user_id == current_user.id  %>
              <%= link_to t('delete_photo'),album_photo_path(photo.album,photo),method: :delete,data:{confirm: t('confirm')} %>
            <% end %>
          <% end %>
        </span>
      </p>
    </div>
  </div>
</div>

app/views/photos/edit.html.erb
<h2><%= t('edit_photo') %></h2>
<br/>
<%= render partial: 'form' %>

app/views/photos/index.html.erb
<p>
  <% breadcrumb :photos %>
</p>

<h2><%= t('photos') %></h2>
<br/>

<p>
  <%= link_to t('btn_back'), albums_path, class: 'btn btn-info' %>
</p>
<hr>
<div class="carousel slide" id="carousel-435758">

  <ol class="carousel-indicators">
    <% @photos.each_with_index do |photo, index| %>
        <li data-slide-to="<%= index %>" data-target="#carousel-435758">
        </li>
    <% end %>

  </ol>
  <div class="carousel-inner">
    <% @photos.each do |photo| %>
      <div class="item">
        <%= link_to image_tag(photo.image, {height:778, width:1170}),album_photo_path(photo.album, photo) %>
        <div class="carousel-caption">
          <h4>
            <%= photo.title %>
          </h4>
          <p>
            <%= photo.description %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
  <a id="left" data-slide="prev" href="#carousel-435758" class="left carousel-control">‹</a>
  <a id="right" data-slide="next" href="#carousel-435758" class="right carousel-control">›</a>
</div>

<script>
    $(function(){
        $('.carousel-indicators > li').first().addClass('active');
        $('.item').first().addClass('active');
    });
</script>

<p>
  <br/>
  <h3><%= t('overview') %></h3>
  <p>
    <% @photos.each do |photo| %>
      <%= link_to image_tag(photo.image,:size=>'240x180',:border=> 0),album_photo_path(photo.album, photo) %>
    <% end %>
  </p>
</p>

app/views/photos/new.html.erb
<h2><%= t('new_photo') %></h2>
<br/>
<%= link_to t('btn_back'), album_path(@album), class: 'btn btn-info' %>
<br/>
<br/>
<%= render 'photos/form' %>

app/views/photos/show.html.erb
<p>
  <% breadcrumb :photo, @photo %>
</p>

<%= link_to t('btn_back'), album_path(@photo.album), class: 'btn btn-info' %>
<%= link_to t('to_home'), welcome_index_path, class: 'btn btn-info' %>

<% if current_user != nil %>
  <% if @photo.user_id == current_user.id  %>
    <%= link_to t('edit'), edit_album_photo_path(@album, @photo), class: 'btn btn-warning', id: 'editLink' %>
  <% end %>
<% end %>
<br/>
<br/>

<div class="carousel slide" id="carousel-435758">
  <ol class="carousel-indicators">
    <% @photos.each_with_index do |photo, index| %>
        <% active = (@photo.id == photo.id)? 'active' : '' %>
        <li class="<%= active %>" img_url="<%= edit_album_photo_path(photo.album, photo) %>" >
        </li>
    <% end %>

  </ol>
  <div class="carousel-inner">
    <% @photos.each do |photo| %>
        <% active = (@photo.id == photo.id)? 'active' : '' %>

        <div class="item <%= active %>">
          <%= image_tag(photo.image, {height:778, width:1170}) %>
          <div class="carousel-caption">
            <h4>
              <%= photo.title %>
            </h4>
            <p>
              <%= photo.description %>
            </p>
          </div>
        </div>
    <% end %>
  </div>
  <a id="left" data-slide="prev" href="#carousel-435758" class="left carousel-control">‹</a>
  <a id="right" data-slide="next" href="#carousel-435758" class="right carousel-control">›</a>
</div>

<% if @photo.private %>
    <p style="color:#2efd00"><%= t('private') %></p>
<% else %>
    <p style="color:#fd7a00"><%= t('public') %></p>
<% end %>
<span style="float:right">
  <%= @user.username %>
</span>

<p>
  <h3><%= t('comments') %></h3>
  <ul class="list-group">
    <%= render @photo.comments %>
  </ul>
</p>

<p>
  <h4><%= t('new_comment') %></h4>
  <%= render 'comments/form' %>
</p>

<script>
    $(function() {
        $('.carousel').carousel('pause');
        $('#right').click(function() {
            if($('li.active').prev() == null){
                var link = $('li.active').first().attr('img_url');
            }else{
                var link = $('li.active').next().attr('img_url');
            }
            $('#editLink').attr('href', link);
        });

        $('#left').click(function() {

            if($('li.active').prev() == null){
                var link = $('li.active').last().attr('img_url');
            }else{
                var link = $('li.active').prev().attr('img_url');
            }

            $('#editLink').attr('href', link);
        });
    });

</script>

app/views/welcome/index.html.erb
<h2><%= t('albums') %></h2>
<hr>
<br/>
<% @albums.each do |album| %>
  <p>
    <h3><%= album.title %></h3>
      <p>
        <%= album.description %>
      </p>
      <%= link_to t('more'), album %>
  </p>
  <br/>
<% end %>